apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-music
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-music
    apps.tanzu.vmware.com/has-tests: "false"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/cloudfoundry-samples/spring-music
  serviceClaims:
    - name: db
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: pg-instance-spring-music

