apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-music
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-music
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/cloudfoundry-samples/spring-music
